---
#- name: install software-properties-common
#  apt:
#    name: software-properties-common
#    cache_valid_time: "{{ kodi_apt_cache_valid_time }}"
#  become: true
#  when: kodi_repository != ""

- name: ensure apt update
  apt:
    update_cache: true
  become: true

- name: install gpg packages
  apt:
    name:
      - gpg
      - gpg-agent
    cache_valid_time: "{{ kodi_apt_cache_valid_time }}"
    update_cache: true
  become: true
  when: kodi_repository != ""

- name: add repository key
  apt_key:
    data: "{{ lookup('file', 'apt-key_648ACFD622F3D138.gpg') }}"
    state: present
  become: true

- name: add repository
  apt_repository:
    repo: "{{ kodi_repository }}"
  become: true
  when: kodi_repository != ""

- name: install kodi
  apt:
    name: "{{ kodi_packages }}"
    default_release: "{{ kodi_release if kodi_release != '' else omit }}"
    cache_valid_time: "{{ kodi_apt_cache_valid_time }}"
  become: true

- name: enable kodi
  systemd:
    name: kodi
    state: started
    enabled: true
    daemon_reload: true
  become: true
